version: 2.1
jobs:
  build_test:
    docker:
      -image: circleci/node:12
    steps:
      - checkout
      - run:
          name: install npm dependencies
          command:
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:12
    steps:
      - checkout 
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
              docker build -t nodejswebapp1 -t adijaiswal/nodejswebapp1:latest.
              echo $DOCKER_PASSWORD | docker login -u adijaiswal --password-stdin
              docker push adijaiswal/nodejswebapp:latest
workflows:
  build_test:
    jobs: 
      - build_test
      - build_docuer_image
                    

